! This program generates the initial conditions for the SIS model
! The initial conditions are stored in a file defined in inputs.nml
! The initial conditions are generated by randomly infecting N_infected nodes
! Author: Aina Gaya Avila

program generate_ICs

    use :: network_analysis
    use :: dynamics

    implicit none

    ! Number of infected nodes
    integer :: N_infected
    ! Simulation parameters (from the namelist)
    real :: ti, tf, dt, lambda, delta
    ! Number of nodes and edges in the network
    integer :: N, edges
    ! Resulting list of infected nodes
    integer, allocatable :: list_infected(:)
    ! Pair list for the network
    integer, allocatable :: pair_list(:, :)
    ! Network filename
    character(len=100) :: network
    ! Iterator
    integer :: i
    ! Name of the file to store the initial conditions
    character(len=100) :: IC_file
    ! Seed for the random number generator
    integer, allocatable :: seed(:)
    integer :: nn, s

    ! Read values from namelist
    namelist /parameters/ N_infected, ti, tf, dt, lambda, delta, IC_file

    ! Set seed for random number generator
    s = 5
    call random_seed(size=nn)
    allocate(seed(nn))
    seed = s    ! putting arbitrary seed to all elements
    call random_seed(put=seed)
    deallocate(seed)

    print*, "Enter the network filename: "  
    read(*,*) network

    open(unit=10, file='input.nml', status='old')
    read(10, parameters)
    close(10)

    call read_network(network, pair_list, N, edges)

    allocate(list_infected(N))

    list_infected = 0

    call infect_random(N, N_infected, list_infected)

    print*, "Randomly infected nodes", list_infected(:N_infected)

    open(unit=10, file=IC_file)

    do i = 1, N
        write(10, *) list_infected(i)
    end do

    close(10)

end program